### ISSUE TITLE
I think I broke Peaks

### ISSUE THREAD

**Issue by Joyc3Th3Max** [vegeta897/wordle-peaks#10]
Hello dear Wordle Peaks team,

I was just casually playing along my daily game when I suddenly lost my internet connection and now my game is broken. It keeps telling me "loading..." but will stay like that at all times. I can click the question mark and options buttons but their display won't open properly (it shows me that I've clicked the button, by getting darker, but the window won't open). I hope that I've explained this well enough for you to understand what is happening and to maybe find a solution to it.

Thank you and with kind regards

**Comment by vegeta897** [comment]
Hello, I'm sorry for the trouble.

Can you tell me whether you're on desktop or mobile, and which browser you're using?

If you're on desktop, can you try a [**hard refresh**](https://fabricdigital.co.nz/assets/How-to-hard-refresh-browser-infographic.jpg) while on Wordle Peaks to see if that fixes it?

**Comment by Joyc3Th3Max** [comment]
Hello and thank you for your quick answer!
I am currently on mobile and I'm using a short cut I pinned to my main
display. I've also tried removing it and accessing it normally but nothing
seems to fix the issue

A segunda, 2/05/2022, 13:57, Devin Spikowski ***@***.***>
escreveu:

**Comment by vegeta897** [comment]
Are you using the Safari browser on iPhone?

**Comment by vegeta897** [comment]
I just pushed [an update](https://twitter.com/vegeta897/status/1522227800333238273) (commit 71a6021822d606f8f9e8d63dffbab37715bb4e39) that may fix this issue for you, can you please try again and let me know?

**Comment by Joyc3Th3Max** [comment]
Good evening,

It works now! Thank you so much for fixing this issue so quickly! 👍

A quinta, 5/05/2022, 16:55, Devin Spikowski ***@***.***>
escreveu:

**Comment by vegeta897** [comment]
I'm so happy to hear that! Thank you for letting me know!

**Comment by Joyc3Th3Max** [comment]
Nope regular Chrome on a Samsung 🙊

A segunda, 2/05/2022, 14:10, Devin Spikowski ***@***.***>
escreveu:

**Comment by vegeta897** [comment]
> Nope regular Chrome on a Samsung 🙊

Oh hello, was this just for my information, or is the game having issues again?

**Comment by Joyc3Th3Max** [comment]
Hello :)
Nope it is wprking fine now that's for asking tho!
Nice regards

A terça, 11/10/2022, 11:09, Devin Spikowski ***@***.***>
escreveu:
