### ISSUE TITLE
Please make idlers(?) optional

### ISSUE THREAD

**Issue by esiegerman** [vegeta897/wordle-peaks#15]
I find the dancing letters in unfilled squares (I think they're called "idlers") to be very distracting.[*]  In order to concentrate on my guesses, I have to cover them up with one hand turned sideways, while holding my phone with the other -- quite awkward.

If they could be made turn-off-able with a preference setting, that would be very much appreciated.

Thanks.

[*] The same is true of animated ads and the like.  Assorted *stuff* moving on my screen, unrelated to the operation I'm actively performing, is a problem.  I guess a lot of people are able to filter out such distractions, but there are those of us who aren't.

**Comment by vegeta897** [comment]
Good suggestion, thanks. I didn't think they would be a bother while playing since they don't appear unless the app gets no input for some time, and when I'm trying to form guesses I'm typing and deleting letters to find a word. I will add an option to turn them off.
