### ISSUE TITLE
RFE: Don't show if a word is valid until I hit enter

### ISSUE THREAD

**Issue by jayofdoom** [vegeta897/wordle-peaks#26]
When I'm solving a puzzle, I don't want to know if the current word is valid until I hit enter. It'd be nice to be able to have a toggle for this behavior.

Thanks!

**Comment by vegeta897** [comment]
Interesting, can you explain your reasoning behind this preference?

**Comment by jayofdoom** [comment]
It significantly reduces the difficulty when I see that a word exists while I'm working through different possible solutions. In a recent puzzle (and in times past) this has happened where an acceptable word was stumbled on while trying to find a valid answer.

**Comment by vegeta897** [comment]
Gotcha, I can see that. Thanks for the suggestion!
