### ISSUE TITLE
Share button shows share options, how to actually share?

### ISSUE THREAD

**Issue by giddyhup** [vegeta897/wordle-peaks#27]
I must be missing something but clicking Share show the sharing options and I don‘t see a way get something on the clipboard. There is no "Accept Options and Share" button. The options only go away by reloading the page. (Safari, iPadOS 18.2)

**Comment by vegeta897** [comment]
Hi, I'm sorry about the confusion! After you click the Share button and review the options, you must click on the "Text" or "Image" button, which will then copy your score in text or image form.

I already plan on reworking this design, because you're not the first person to bring this to my attention. Thank you for adding another voice!

**Comment by giddyhup** [comment]
Thanks for the quick reply. I didn‘t understand your response until I looked at the site with a desktop browser and then it clicked. The buttons do not appear on my iPad. 

![IMG_5454](https://github.com/user-attachments/assets/e9cc6d05-8bcb-4e2b-92c6-c072348e2d61)

It may be my adblockers which are causing this. I will try to see if disabling them helps.

**Comment by vegeta897** [comment]
Uh oh, that's not good at all! I'd be surprised if they were being ad-blocked, but I don't know what is happening here.

My iPad isn't on 18.2 yet so I can't test this myself right away, but I'll try to do that soon.

**Comment by giddyhup** [comment]
The issues seems to lie with the grid of the classes "share-buttons svelte-abjg2o". A quick google shows that there were issues with Safari and grids in the past. Firefox on the same iPad shows the buttons.

Unrelated: the language picker for German should say "Deutsch" and not "Deutsche".  (The language alone is "Deutsch", only if you add "Sprache" the "e" would be appended ("Deutsche Sprache", "German language"). Lastly, perhaps you'd want to call that option Interface Language since people may think the dictionary is also changed, I did at first.

**Comment by vegeta897** [comment]
Hmm, that doesn't seem right, because the share button itself is in the same kind of grid (the `action-items` class).

Thanks for the tip on Deutsch (e30e7acf6dec391dd37e06051c5c66865c376ec9)! I'll have to think more about the language option name.

**Comment by vegeta897** [comment]
I just updated to 18.2 and I'm still not seeing this issue in Safari.

My only guess is some kind of cache issue, but I understand if you don't want to clear that.

**Comment by giddyhup** [comment]
It was AdBlock Pro. In particular the option "3. Social". Sorry about opening an issue, at least I could help with one comment regarding localization.

**Comment by vegeta897** [comment]
Aha, I had suspected something like that but didn't really think it could be the reason. It's actually wild to me that an ad blocker would just indiscriminately target classes by name alone (share-buttons) but now I know, and I can do some renaming.

You did help a lot here by identifying the cause, please don't apologize. You probably aren't the only one who has this issue, so it's worth fixing, and I'm happy to have the new piece of knowledge. I appreciate it!
